dataset: ogbg-molhiv
model:
  hidden_size: 128
  num_layers: 2
  mini_layers: 1
  pool: mean
  embs: (0, 2)
  embs_combine_mode: 'add'
subgraph:
  hops: 3
  online: True
train:
  lr_patience: 50
  dropout: 0.3
  epochs: 60
  runs: 5