dataset: ZINC
model:
  num_layers: 6
  mini_layers: 1
  embs: (0, 1, 2)
  embs_combine_mode: 'concat'
  pool: add
subgraph:
  hops: 3
  online: True
  # walk_length: 15
  # walk_p: 1.
  # walk_q: 4
  # walk_repeat: 5
train:
  epochs: 310


